baseurl                  = "https://robinette.dev/"           # Your domain name. Must end with "/"
languageCode             = "en-us"
defaultContentLanguage   = "en"
isMultilingual           = false
title                    = "Food, Coffee, Code"
theme                    = "sam"
pygmentsStyle            = "monokai"                        # https://help.farbox.com/pygments.html
pygmentsCodefences       = true
# googleAnalytics        = ""                               # Tracking code, eg. "UA-111111111-1"

[params]
    dateform             = "Mon Jan 02, 2006"
    dateformfull         = "Mon Jan 2 2006 15:04:05 EST"
    favicon              = "favicon.png"
    homepage             = "main"                           # What to call the home page link
    footerText           = "Hello my name is Calen."

# Metadata for Open Graph and Twitter
    description          = "Thoughts, Code and Notes by Calen Robinette"               # Max 160 characters show in search results
    # images               = ["tn.png"]                       # Image that shows on Twitter cards and Open Graph links to the site
    title                = "Calen Robinette's blog"

[[params.mainMenu]]
    link = "/posts"
    text = "blog"

[[params.mainMenu]]
    link = "https://github.com/calenrobinette"
    text = "code"

[[params.mainMenu]]
    link = "/notes"
    text = "notes"

[[params.mainMenu]]
    link = "/about"
    text = "about"

[imaging]
    quality = 75
